//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int FineID { get; set; }
        public Nullable<int> LateDays { get; set; }
        public Nullable<int> StaffMemberID { get; set; }
        public string Amount { get; set; }
        public string Remarks { get; set; }
    
        public virtual MemberCategory MemberCategory { get; set; }
    }
}
